/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Build-time packaging step: read the hand-curated rhythm catalog at
 * `Notes/all-rhythms.txt` and emit a generated TypeScript module
 * `src/lib/rhythm-catalog-data.ts` exporting the catalog text as a string
 * constant. The runtime parser imports the string from this generated
 * module so the catalog is bundled into the worker at build time with no
 * runtime file-system read.
 *
 * `Notes/all-rhythms.txt` remains the hand-curated source of truth; this
 * script only packages it. The generated module is a build artifact and is
 * gitignored, like `schema.sql`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..')
const SOURCE = join(REPO_ROOT, 'Notes', 'all-rhythms.txt')
const OUTPUT = join(REPO_ROOT, 'src', 'lib', 'rhythm-catalog-data.ts')

const text = readFileSync(SOURCE, 'utf8')

const output = `/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * GENERATED by scripts/package-rhythm-catalog.ts — do not edit by hand.
 *
 * The packaged rhythm catalog text, copied from Notes/all-rhythms.txt at
 * build time. The runtime parser in src/lib/rhythm-catalog.ts imports this
 * string so the catalog is bundled into the worker with no runtime
 * file-system read. Notes/all-rhythms.txt remains the hand-curated source
 * of truth; rerun \`npm run package-rhythm-catalog\` (or \`npm run build\`,
 * which runs it via prebuild) to regenerate after editing the catalog.
 */
export const RHYTHM_CATALOG_TEXT: string = ${JSON.stringify(text)}
`

writeFileSync(OUTPUT, output)
console.log(`Packaged rhythm catalog: ${SOURCE} -> ${OUTPUT}`)
